# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ad5a95a28fa9b1e29b35e79a993d0d5986ca72147860a5eb1e05a29849d7884328eb071ba02355ff5c2879f47f5abcb0138b2c6827ce651b207ff60e7e5ac68

test:
  secret_key_base: 89c3be9fcdf755b597781b1470db065b2605fd627bef38fad3a0a9ea2184cb3219f930036000bcf6b24a43f829c90c2faee688860e1004782e8840ec4e2c298c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
